// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/perfectbuii/gen-go-template/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// TeamRepository is an autogenerated mock type for the TeamRepository type
type TeamRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, team
func (_m *TeamRepository) Create(ctx context.Context, team *models.Team) error {
	ret := _m.Called(ctx, team)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Team) error); ok {
		r0 = rf(ctx, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Delete provides a mock function with given fields: ctx, id
func (_m *TeamRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *TeamRepository) GetByID(ctx context.Context, id string) (*models.Team, error) {
	ret := _m.Called(ctx, id)

	var r0 *models.Team
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Team); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetList provides a mock function with given fields: ctx, offset, limit
func (_m *TeamRepository) GetList(ctx context.Context, offset int, limit int) ([]*models.Team, error) {
	ret := _m.Called(ctx, offset, limit)

	var r0 []*models.Team
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Team); ok {
		r0 = rf(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Team)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, team
func (_m *TeamRepository) Update(ctx context.Context, id string, team *models.Team) error {
	ret := _m.Called(ctx, id, team)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, *models.Team) error); ok {
		r0 = rf(ctx, id, team)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewTeamRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewTeamRepository creates a new instance of TeamRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewTeamRepository(t mockConstructorTestingTNewTeamRepository) *TeamRepository {
	mock := &TeamRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
